[build-system]
requires = ["setuptools>=66.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[project]
name = "demo_app"
version = "0.1"
dependencies = [
    'fastapi',
    'dishka',
    'uvicorn',
]
